In [7]:
import numpy as np

In [6]:
#Ques 1
x=np.random.rand(10,1)

In [7]:
np.mean(x)

0.5580092138658918

In [17]:
#Ques 2
y=np.random.rand(20,1)

In [18]:
np.std(y)

0.2413861002190758

In [19]:
np.var(y)

0.05826724937897371

In [20]:
#Ques 3
A=np.random.rand(10,20)
B=np.random.rand(20,25)

In [22]:
C=np.matmul(A,B)
C

array([[3.0856265 , 3.10987108, 3.76864287, 3.86060849, 4.08390062,
        4.16565061, 3.14534645, 4.48081021, 3.91814082, 4.18776501,
        3.12859806, 3.03526977, 3.62814905, 3.90038337, 4.11860043,
        3.49734166, 4.0946737 , 2.96494728, 3.18145253, 3.86304619,
        3.81384223, 4.37914762, 2.97741036, 3.91383137, 3.71050117],
       [3.15617793, 3.41789918, 3.40629416, 3.16452654, 3.01291494,
        3.37315906, 3.04319092, 3.49659388, 3.1745612 , 3.64563193,
        3.1071486 , 3.22068612, 3.3125088 , 3.54520355, 4.25276566,
        3.53015076, 2.38897717, 3.61598932, 3.51933792, 4.15830128,
        2.8927978 , 3.88301302, 3.20078046, 2.7904921 , 3.6027213 ],
       [4.14294179, 4.53813383, 5.71766308, 4.4237607 , 4.0351977 ,
        3.88343781, 4.25470844, 4.22984322, 3.78551845, 4.67198445,
        3.44984117, 3.46298634, 4.4615672 , 4.9888817 , 4.63844765,
        4.03182554, 4.25098307, 3.85102952, 3.94309095, 4.93555314,
        3.73187879, 4.72176178, 3.9453368 , 4.

In [25]:
np.sum(C)

1114.019482801297

In [26]:
C.shape

(10, 25)

In [21]:
#Ques 4
A=np.random.rand(10,1)
A

array([[0.34015829],
       [0.65203512],
       [0.34818556],
       [0.69858557],
       [0.38500144],
       [0.91352012],
       [0.69982753],
       [0.88634132],
       [0.86445731],
       [0.70536954]])

In [22]:
def fun(x):
    a=(1/(1+np.exp(-x)))
    return a

In [23]:
np.apply_along_axis(fun,0,A)

array([[0.58422897],
       [0.65746892],
       [0.58617751],
       [0.6678741 ],
       [0.59507882],
       [0.71371995],
       [0.66814953],
       [0.70813457],
       [0.70359107],
       [0.66937719]])